apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-gitops

resources:
  # Operators managed by ArgoCD
  - platform-operators.yaml

  # Platform components
  - kyverno.yaml
  - kyverno-policies.yaml

  # Applications
  - grafana-instance.yaml

  # Comment out any app to exclude it from deployment
