apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  namespace: grafana
  labels:
    dashboards: grafana
spec:
  config:
    server:
      root_url: https://grafana-route-grafana.apps-crc.testing
    auth:
      disable_login_form: "false"
      disable_signout_menu: "false"
    auth.generic_oauth:
      enabled: "true"
      name: OpenShift
      allow_sign_up: "true"
      client_id: grafana
      client_secret: ${GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET}
      scopes: user:full
      auth_url: https://oauth-openshift.apps-crc.testing/oauth/authorize
      token_url: https://oauth-openshift.apps-crc.testing/oauth/token
      api_url: https://kubernetes.default.svc/apis/user.openshift.io/v1/users/~
      tls_skip_verify_insecure: "true"
      login_attribute_path: metadata.name
      name_attribute_path: metadata.name
      email_attribute_path: metadata.name
      role_attribute_path: "'Admin'"
      use_pkce: "true"
  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: grafana-oauth-secret
                      key: client-secret
  route:
    spec:
      tls:
        termination: edge
