apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - remove-resource-limits.yaml
  # Add more policies here as you create them
  # - policy-require-labels.yaml
  # - policy-disallow-privileged.yaml
