apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: kyverno-policies:kyverno.io/ClusterPolicy:/remove-resource-limits
    policies.kyverno.io/category: Resource Management
    policies.kyverno.io/description: >-
      Removes resource requests and limits from all pods. Used on CRC to allow
      pods to run without resource constraints.
    policies.kyverno.io/title: Remove Resource Limits
  name: remove-resource-limits
spec:
  admission: true
  background: true
  emitWarning: false
  rules:
    - match:
        any:
          - resources:
              kinds:
                - Pod
      mutate:
        patchStrategicMerge:
          spec:
            containers:
              - (name): '*'
                resources: {}
            initContainers:
              - (name): '*'
                resources: {}
      name: remove-resources
      skipBackgroundRequests: true
  validationFailureAction: Audit
